import sys

# Fix SQLite version for ChromaDB
__import__("pysqlite3")
sys.modules["sqlite3"] = sys.modules.pop("pysqlite3")


import streamlit as st
from openai import OpenAI
import chromadb
from bs4 import BeautifulSoup
import os
import json


# --------------------------------------------------
# Page Title
# --------------------------------------------------

st.title("HW 5 - Intelligent Student Organization Chatbot")

st.write(
    "Ask me questions about Syracuse University student organizations."
)


# --------------------------------------------------
# OpenAI Client
# --------------------------------------------------

openai_api_key = st.secrets["OPENAI_API_KEY"]

client = OpenAI(
    api_key=openai_api_key
)


# --------------------------------------------------
# Function to Read HTML
# --------------------------------------------------

def read_html(file_path):

    with open(
        file_path,
        "r",
        encoding="utf-8",
        errors="ignore"
    ) as file:

        html_content = file.read()

    # Remove HTML tags and return readable text
    soup = BeautifulSoup(
        html_content,
        "html.parser"
    )

    # Remove script and style content
    for element in soup(["script", "style"]):
        element.decompose()

    text = soup.get_text(
        separator=" ",
        strip=True
    )

    return text


# --------------------------------------------------
# Split Each HTML Document
# into Exactly Two Mini-Documents
# --------------------------------------------------

def split_into_two_chunks(text):

    words = text.split()

    middle = len(words) // 2

    first_chunk = " ".join(
        words[:middle]
    )

    second_chunk = " ".join(
        words[middle:]
    )

    return [
        first_chunk,
        second_chunk
    ]


# --------------------------------------------------
# Create Embedding
# --------------------------------------------------

def create_embedding(text):

    response = client.embeddings.create(
        model="text-embedding-3-small",
        input=text
    )

    return response.data[0].embedding


# --------------------------------------------------
# Load Existing HW4 Chroma Database
# --------------------------------------------------

# We reuse the HW4 database because it already contains
# the student organization documents and embeddings.

chroma_client = chromadb.PersistentClient(
    path="HW4_ChromaDB"
)

collection = chroma_client.get_or_create_collection(
    name="HW4Collection"
)


# --------------------------------------------------
# Create Database Only If Empty
# --------------------------------------------------

if collection.count() == 0:

    with st.spinner(
        "Creating vector database from student organization pages..."
    ):

        html_folder = "HW4_Data"

        html_files = [
            file
            for file in os.listdir(html_folder)
            if file.lower().endswith(".html")
        ]

        document_id = 0

        for filename in html_files:

            file_path = os.path.join(
                html_folder,
                filename
            )

            document_text = read_html(
                file_path
            )

            chunks = split_into_two_chunks(
                document_text
            )

            for chunk_number, chunk in enumerate(chunks):

                if not chunk.strip():
                    continue

                embedding = create_embedding(
                    chunk
                )

                collection.add(
                    ids=[str(document_id)],
                    documents=[chunk],
                    embeddings=[embedding],
                    metadatas=[
                        {
                            "filename": filename,
                            "chunk": chunk_number + 1
                        }
                    ]
                )

                document_id += 1


# Store collection in session state
st.session_state.HW5_VectorDB = collection


# --------------------------------------------------
# Tool Function
# --------------------------------------------------

def relevant_club_info(query):

    """
    Search the ChromaDB collection using a query
    generated by the LLM and return relevant
    student organization information.
    """

    query_embedding = create_embedding(
        query
    )

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=6
    )

    retrieved_documents = (
        results["documents"][0]
    )

    retrieved_metadata = (
        results["metadatas"][0]
    )

    rag_context = ""

    for document, metadata in zip(
        retrieved_documents,
        retrieved_metadata
    ):

        rag_context += (
            f"\n\nSource: {metadata['filename']}\n"
            f"{document}"
        )

    return rag_context


# --------------------------------------------------
# Tool Definition for OpenAI
# --------------------------------------------------

club_tool = {
    "type": "function",
    "function": {
        "name": "relevant_club_info",
        "description": (
            "Search the Syracuse University student organization "
            "documents for information relevant to the user's question. "
            "Use this tool when information about student organizations, "
            "clubs, activities, purposes, events, membership, or related "
            "organization details is needed."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": (
                        "A clear search query created from the user's "
                        "question and conversation context. The query "
                        "should describe the student organization "
                        "information that needs to be retrieved."
                    )
                }
            },
            "required": ["query"]
        }
    }
}


# --------------------------------------------------
# System Prompt
# --------------------------------------------------

system_prompt = {
    "role": "system",
    "content": (
        "You are a helpful Syracuse University student "
        "organization chatbot. "

        "Answer questions using simple and clear language. "

        "For questions that require information about Syracuse "
        "University student organizations, use the "
        "relevant_club_info tool to search the provided documents. "

        "Create a useful search query for the tool based on the "
        "user's current question and the recent conversation. "

        "If the user asks a follow-up question such as "
        "'tell me more about it' or 'what activities do they do?', "
        "use the conversation memory to understand what organization "
        "the user is referring to. "

        "Do not invent organization names, activities, contact "
        "information, membership details, or other facts. "

        "If relevant information cannot be found in the provided "
        "student organization documents, clearly tell the user that "
        "the information could not be found."
    )
}


# --------------------------------------------------
# Chat Memory
# --------------------------------------------------

if "hw5_messages" not in st.session_state:
    st.session_state.hw5_messages = []


# Display previous messages
for message in st.session_state.hw5_messages:

    with st.chat_message(message["role"]):
        st.markdown(message["content"])


# --------------------------------------------------
# Chat Input
# --------------------------------------------------

if prompt := st.chat_input(
    "Ask about a student organization..."
):

    user_message = {
        "role": "user",
        "content": prompt
    }

    st.session_state.hw5_messages.append(
        user_message
    )

    with st.chat_message("user"):
        st.markdown(prompt)


    # --------------------------------------------------
    # Short-Term Memory
    # Keep Last 5 Complete Interactions
    # --------------------------------------------------

    previous_messages = (
        st.session_state.hw5_messages[:-1]
    )

    exchanges = []
    current_exchange = []

    for message in previous_messages:

        if message["role"] == "user":

            if current_exchange:
                exchanges.append(
                    current_exchange
                )

            current_exchange = [
                message
            ]

        elif (
            message["role"] == "assistant"
            and current_exchange
        ):

            current_exchange.append(
                message
            )

            exchanges.append(
                current_exchange
            )

            current_exchange = []


    recent_messages = []

    # Keep the last 5 user/assistant interactions
    for exchange in exchanges[-5:]:

        recent_messages.extend(
            exchange
        )


    # Add current user question
    recent_messages.append(
        user_message
    )


    # --------------------------------------------------
    # First LLM Call
    #
    # The LLM decides whether it needs the tool.
    # The LLM also creates the query that will
    # be sent to relevant_club_info.
    # --------------------------------------------------

    messages_for_api = [
        system_prompt,
        *recent_messages
    ]

    first_response = client.chat.completions.create(
        model="gpt-5-mini",
        messages=messages_for_api,
        tools=[club_tool],
        tool_choice="auto"
    )

    assistant_message = (
        first_response.choices[0].message
    )


    # --------------------------------------------------
    # If LLM Requests the Tool
    # --------------------------------------------------

    if assistant_message.tool_calls:

        tool_call = (
            assistant_message.tool_calls[0]
        )

        arguments = json.loads(
            tool_call.function.arguments
        )

        llm_query = arguments.get(
            "query",
            prompt
        )


        # --------------------------------------------------
        # Run Vector Search ONLY After LLM
        # Requests the Tool
        # --------------------------------------------------

        retrieved_information = (
            relevant_club_info(
                llm_query
            )
        )


        # --------------------------------------------------
        # Add LLM Tool Request to Conversation
        # --------------------------------------------------

        messages_for_api.append(
            {
                "role": "assistant",
                "content": assistant_message.content,
                "tool_calls": [
                    {
                        "id": tool_call.id,
                        "type": "function",
                        "function": {
                            "name": (
                                tool_call.function.name
                            ),
                            "arguments": (
                                tool_call.function.arguments
                            )
                        }
                    }
                ]
            }
        )


        # --------------------------------------------------
        # Add Tool Result
        # --------------------------------------------------

        messages_for_api.append(
            {
                "role": "tool",
                "tool_call_id": tool_call.id,
                "content": retrieved_information
            }
        )


        # --------------------------------------------------
        # Additional Instructions for Final Answer
        # --------------------------------------------------

        messages_for_api.append(
            {
                "role": "system",
                "content": (
                    "Use the student organization information "
                    "returned by the tool to answer the user's "
                    "question. "

                    "Answer only using the retrieved information. "

                    "If the retrieved information contains the "
                    "answer, begin with: "
                    "'Based on the retrieved student organization "
                    "information:' "

                    "If only part of the answer is available, "
                    "explain what was found and clearly state what "
                    "was not found. "

                    "If the answer cannot be found in the retrieved "
                    "information, say: "
                    "'I could not find this information in the "
                    "provided student organization documents.' "

                    "Do not invent any information. "
                    "Keep the answer simple and clear."
                )
            }
        )


        # --------------------------------------------------
        # Second LLM Call
        #
        # IMPORTANT:
        # No tools are provided here.
        # The model must answer using the retrieved results.
        # --------------------------------------------------

        with st.chat_message("assistant"):

            stream = client.chat.completions.create(
                model="gpt-5-mini",
                messages=messages_for_api,
                stream=True
            )

            response = st.write_stream(
                stream
            )


    # --------------------------------------------------
    # If LLM Does Not Request Tool
    # --------------------------------------------------

    else:

        response = assistant_message.content

        if not response:
            response = (
                "I could not determine how to answer that "
                "question. Please try asking it in a different way."
            )

        with st.chat_message("assistant"):
            st.markdown(response)


    # --------------------------------------------------
    # Save Assistant Response to Memory
    # --------------------------------------------------

    st.session_state.hw5_messages.append(
        {
            "role": "assistant",
            "content": response
        }
    )